package kits.bioinfo.core;

import org.junit.Assert;
import org.junit.Test;

public class RibosomeTest {

	@Test
	public void test1() {
		RnaSequence rnaSequence = new RnaSequence("AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA");
		
		Peptid peptid = new Ribosome().translateToAminoAcidSequence(rnaSequence);
		
		Assert.assertEquals("MAMAPRTEINSTRING", peptid.toString());
	}
	
	@Test
	public void test2() {
		RnaSequence rnaSequence = new RnaSequence("AUGAGAGGUCCCGGGACUACGUGUUCUAGAAUCAGUCGCGGGGAUGUCAAUCCAUCAGGGAAUCAUUUAGUACUGGUGCGAUUAGCAGCCACCAGGCCUUGGGUGGUUCGACGGGCUUACGACCCCCGAUCGGACAAAGUCGAGCAGGCACAUAAAAGACCAGGCGCAGUUCAGAUACGCGUGAGCAAAGUUUCGGCGAACCAUUUUCCCUUGCCUUGUAUGGAAGUGCUUCUAGUUGUAGCAUCGAGCUUACGAAAAGCGGGGAUUCUCUUGCACCGCUGGUCCAUGUCAGGGUCCUUUUUCAUUCCCUCAGAUACUUAUCCCCAAAUCACUUGCAGAG");
		
		Peptid peptid = new Ribosome().translateToAminoAcidSequence(rnaSequence);
		
		Assert.assertEquals("MRGPGTTCSRISRGDVNPSGNHLVLVRLAATRPWVVRRAYDPRSDKVEQAHKRPGAVQIRVSKVSANHFPLPCMEVLLVVASSLRKAGILLHRWSMSGSFFIPSDTYPQITCR", peptid.toString());
	}
	
}
